### ISSUE TITLE
Readmeの更新について

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#1]
プロジェクト導入手順をReadmeへ記載をお願いします。
他にもプロジェクトに関する情報もできたところまででも良いので
書いてください。

ジュンソンさんのプロジェクトを参考してみてください。
https://github.com/wnstjd0333/News

**Comment by rlawjdgh930829** [comment]
参考して作成してみまします。 ありがとうございます。

**Comment by kimjeongho930829** [comment]
参考して作成してみます。 ありがとうございます。

**Comment by dolfalf** [comment]
対応できましたらissueをクローズしてください。
