### ISSUE TITLE
오라클 DB에서 PostgreSQL 또는 MySQL로 변경

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#10]
PostgreSQL 또는 MySQL로 데이타베이스를 변경해 보세요. 
아마 프레임워크에서 처리해주는 부분이라 설정정의만 잘 바꿔주면 될거라 생각됩니다.

**Comment by kimjeongho930829** [comment]
MySQL로 변경하고 있습니다.
