### ISSUE TITLE
예외에 대한 처리확인

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#14]
화면마다 로그인이 필요한 화면, 필요하지 않은화면에 대해서 에러 핸들링이 구현되었는지 궁금하군요.
예를들어 로그인화면자체는 로그인이 필요하지 않지만 로그인화면 뒷화면들은 로그인이 되어있지 않으면 어떻게 되나요?
적절히 에러메세지를 표시해주고 로그인화면으로 돌려주게끔 처리가 되어있는지요.

**Comment by kimjeongho930829** [comment]
현재 만들고 있는 댓글 말고는 필터를 통해 로그인 여부를 확인하고 있습니다.
로그인 하지 않은 상태에서 글작성, 글삭제, 글수정에 접근하면 로그인 페이지로 이동하고
만약 글삭제나, 글수정의 경우 로그인은 했지만 다른 작성자가 접근한 경우에는 현재 로그인중인 정보와 글을 작성한 유저의 정보를 비교합니다.
만약 로그인 상태에서 로그인 페이지나 회원가입 페이지로 접근할 경우에는 메인 페이지로 이동하게 했습니다.
페이지 이동만 하고 에러메시지의 생각은 하지 못하였는데 댓글 기능을 마무리하고 추가하도록 하겠습니다.
