### ISSUE TITLE
테스트항목서 작성및 테스트

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#16]
현장에서의 경우 개발업무는 아래와같이 진행됩니다.

## 대략적인 개발과정

1.  요건정의(고객)
2.  설계(엔지니어)
3.  구현(엔지니어)
4.  단위테스트(엔지니어)
5.  결합테스트(엔지니어, 테스터)
6.  시나리오테스트(테스터, 고객)

## 테스트항목서 작성및 테스트 요령
이번에 만든 애플리케이션에서 단위테스트를 위한 테스트항목서 작성 및 테스트를 하시기 바랍니다.

1. 요건정의 -> 만든애플리케이션의 기능을 정리하세요.
2. 설계 -> 각각의 기능들이 어떻게 동작하는 지 정리하세요.
3. 테스트항목서 작성 -> 각각의 기능을 조작하였을때 결과값을 확인할 수있게 테스트항목서를 작성하세요.
4. 테스트 실시 -> NG항목이 발생하더라도 테스트를 일단 끝까지 진행하세요. (더이상 테스트가 진행하기 어려울경우는 예외)
5. 버그수정 -> NG항목에 대해 브랜치(bugfix/xxxx) 작성후 수정
6. 재테스트

## 테스트항목서 작성시 유의사항
- 테스트항목에는 하나의 케이스만 기입할것
- 정상동작이외에 예외상황에 대해서도 테스트케이스에 추가할것
- 테스트항목과 결과를 명확하게 작성할것

## 참고링크
예전에 연수할때 작성된 테스트 항목서 첨부합니다. 복사하셔서 사용하세요.
https://docs.google.com/spreadsheets/d/1ildYc8_QEQsnFQvXGRGp0zWmObNp5W_Du8ws9F8_zBo/edit?usp=sharing

## 관련 프로젝트 리포지토리

https://github.com/vkdlxh/SimpleDocbase

**Comment by kimjeongho930829** [comment]
감사합니다. 참고하여 작성하겠습니다.
