### ISSUE TITLE
変数名、メソッド名、コメントの書き方について

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#2]
以下、レビューした内容です。

- 変数名はキャメルケース(Camel Case)で書くように
- 当たり前のコメントは書くよりは変数名、メソッド名を明確にする
- コミットのコメントはできるだけ詳しく記録する。形式に拘らず書いてください。

https://m.blog.naver.com/PostView.nhn?blogId=playcodingacademy&logNo=221317135750&proxyReferer=https:%2F%2Fwww.google.com%2F

**Comment by kimjeongho930829** [comment]
링크 감사합니다 참고하여 수정하겠습니다

**Comment by dolfalf** [comment]
対応できましたらissueをクローズしてください。
