### ISSUE TITLE
これからの作業はPull Requestを利用するように

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#3]
現場でも直接Pushする場面がないので簡単な作業でもbranchを切って作業しまよう。
このような流れです。

1. 作業のためのbranchを作成
2. 作業が完了したらPushし、PRを作成
3. レビューを受け、修正などを行う
4. レビュー対応が終わったらマージする。（もし、レビューがなくても他の作業に影響が発生する場合は待たずにマージする）

**Comment by kimjeongho930829** [comment]
@kimchangmin-archive

**Comment by dolfalf** [comment]
内容が把握できたらissueをクローズしてください。
