### ISSUE TITLE
코멘트기능 구현하기전에 RDBMS에 대해서 학습해주세요.

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#7]
한글로 찾아보니 잘 안보이네요. 
인터넷강좌도 좋고 블로그도 좋으니 `관계형데이타베이스 설계`, 또는 `관계형 데이타베이스 설명`등으로 검색해서 학습해 보시길 바랍니다.
정규화하는 방법을 이해하고 테이블을 만드는 작업에 대해 감을 잡으면 됩니다.

이건 제가 찾은건데 이것도 다 나온게 아니라서..
https://jepi.tistory.com/132

**Comment by kimjeongho930829** [comment]
링크 감사합니다
