### ISSUE TITLE
변수명, 메소드, 클래스 작명에 대해서

### ISSUE THREAD

**Issue by dolfalf** [rlawjdgh930829/archive-prj#8]
대표적으로 클린코드라는 책이 있는데요. 목적은 명명을 명확히 해서 의미를 정확히 전달함에 있습니다.
경험이 없어도 신경쓰면 개선할수 있는부분이므로 한번 봐두시면 좋을거 같아요.

https://devuna.tistory.com/26
https://woowabros.github.io/study/2019/03/20/cleancode.html

**Comment by kimjeongho930829** [comment]
읽어보고 좀 더 신경써서 작명하겠습니다
